# Generated by Django 5.2.6 on 2025-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='09385965775', max_length=11, unique=True, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
