# Generated by Django 5.2.6 on 2025-10-02 06:33

import account.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_phone_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[155, 155], upload_to=account.models.profile_directory_path, verbose_name='تصویر پروفایل'),
        ),
    ]
