# Generated by Django 5.2.6 on 2025-10-02 06:58

import account.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='Profiles/default_profile.png', force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[155, 155], upload_to=account.models.profile_directory_path, verbose_name='تصویر پروفایل'),
        ),
    ]
