# Generated by Django 5.2.6 on 2025-10-04 14:50

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[account.models.validate_username], verbose_name='نام کاربری'),
        ),
    ]
