# Generated by Django 5.2.6 on 2025-10-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_username'),
        ('media_center', '0013_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, to='media_center.post', verbose_name='تاریخچه'),
        ),
    ]
