# Generated by Django 5.2.6 on 2025-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.CharField(default=(1, 2), max_length=100, verbose_name='تاریخچه'),
            preserve_default=False,
        ),
    ]
