# Generated by Django 5.2.6 on 2025-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_user_history_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخچه'),
        ),
    ]
