# Generated by Django 5.2.6 on 2025-10-20 20:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[account.models.validate_history], verbose_name='تاریخچه'),
        ),
    ]
