# Generated by Django 5.2.6 on 2025-10-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='تاریخچه'),
        ),
    ]
