# Generated by Django 5.2.6 on 2025-10-06 13:37

import django.db.models.deletion
import django_resized.forms
import media_center.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم دسته بندی')),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[155, 155], upload_to='category/thumbnails/')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: دعای جوشن کبیر 1080P', max_length=70, verbose_name='نام مختصر فایل')),
                ('quality', models.CharField(choices=[('144P', '144P'), ('240P', '240P'), ('360P', '360P'), ('480P', '480P'), ('720P', '720P'), ('1080P', '1080P'), ('2K', '2K'), ('4K', '4K')], max_length=5, verbose_name='کیفیت')),
                ('media_type', models.CharField(choices=[('ویدئویی', 'ویدئویی'), ('صوتی', 'صوتی')], max_length=7, verbose_name='نوع فایل')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='اسم')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تیتر پست')),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='140 * 40', keep_meta=True, quality=100, scale=None, size=[240, 240], upload_to=media_center.models.dynamic_post_path, verbose_name='عکس کاور')),
                ('artist', models.CharField(max_length=50, verbose_name='مداح/نویسنده/خواننده ...')),
                ('is_visible', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='دانلود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('categories', models.ManyToManyField(related_name='posts', to='media_center.category', verbose_name='دسته بندی ها')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='لایک شده توسط')),
                ('tags', models.ManyToManyField(related_name='posts', to='media_center.tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='دعای جوشن کبیر', max_length=60, verbose_name='نام رسانه')),
                ('files', models.ManyToManyField(related_name='medias', to='media_center.file', verbose_name='فایل ها')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='media_center.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='کامنت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='نمایش در سایت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_center.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
