# Generated by Django 5.2.6 on 2025-10-06 14:37

import media_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to=media_center.models.dynamic_file_path, verbose_name='فایل'),
            preserve_default=False,
        ),
    ]
