# Generated by Django 5.2.6 on 2025-10-07 14:20

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0002_file_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('profile_picture', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[155, 155], upload_to='Artists/')),
            ],
            options={
                'verbose_name': 'مداح/نویسنده/خواننده',
                'verbose_name_plural': 'مداح/نویسنده/خواننده',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده'),
        ),
        migrations.AddField(
            model_name='media',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='media_center.artist', verbose_name='مداح/نویسنده/خواننده'),
        ),
    ]
