# Generated by Django 5.2.6 on 2025-10-07 14:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0003_artist_remove_post_artist_post_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[155, 155], upload_to='Artists/', verbose_name='غکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[155, 155], upload_to='category/thumbnails/', verbose_name='عکس کاور'),
        ),
    ]
