# Generated by Django 5.2.6 on 2025-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0004_alter_artist_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت زمان پخش محتوا'),
        ),
    ]
