# Generated by Django 5.2.6 on 2025-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0005_file_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommended_by_site',
            field=models.BooleanField(default=False, verbose_name='پیشنهادی سایت'),
        ),
        migrations.AlterField(
            model_name='file',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='برحسب ثانیه', verbose_name='مدت زمان رسانه'),
        ),
    ]
