# Generated by Django 5.2.6 on 2025-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0006_post_recommended_by_site_alter_file_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommended_by_site',
            field=models.BooleanField(default=False, verbose_name='دسته بندی منتخب'),
        ),
    ]
