# Generated by Django 5.2.6 on 2025-10-10 12:12

import media_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0007_category_recommended_by_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=media_center.models.dynamic_file_path, verbose_name='فایل'),
        ),
    ]
