# Generated by Django 5.2.6 on 2025-10-10 12:15

import media_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0009_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to=media_center.models.dynamic_file_path, verbose_name='فایل'),
            preserve_default=False,
        ),
    ]
