# Generated by Django 5.2.6 on 2025-10-10 17:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0010_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[240, 240], upload_to='Artists/', verbose_name='غکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[240, 240], upload_to='category/thumbnails/', verbose_name='عکس کاور'),
        ),
    ]
