# Generated by Django 5.2.6 on 2025-10-16 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0011_alter_artist_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='media_type',
            field=models.CharField(choices=[('video', 'ویدئویی'), ('audio', 'صوتی')], max_length=7, verbose_name='نوع فایل'),
        ),
        migrations.AlterField(
            model_name='file',
            name='quality',
            field=models.CharField(choices=[('144p', '144P'), ('240p', '240P'), ('360p', '360P'), ('480p', '480P'), ('720p', '720P'), ('1080p', '1080P'), ('2560p', '2K'), ('4k', '4K')], max_length=5, verbose_name='کیفیت'),
        ),
    ]
