# Generated by Django 5.2.6 on 2025-10-21 13:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0014_category_level_category_lft_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[240, 240], upload_to='category/thumbnails/', verbose_name='عکس کاور'),
        ),
    ]
