# Generated by Django 5.2.6 on 2025-10-22 17:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django_resized.forms
import media_center.models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0015_alter_category_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='240 * 240', keep_meta=True, quality=100, scale=None, size=[240, 240], upload_to=media_center.models.dynamic_post_path, verbose_name='عکس کاور'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='media_cente_search__517368_gin'),
        ),
    ]
