# Generated by Django 5.2.6 on 2025-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0016_post_search_vector_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم دسته بندی'),
        ),
    ]
