# Generated by Django 5.2.6 on 2025-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0017_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_story',
            field=models.BooleanField(default=False, verbose_name='استوری'),
        ),
    ]
