# Generated by Django 5.2.6 on 2025-11-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0019_alter_comment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='متن اشتراک'),
        ),
    ]
