# Generated by Django 5.2.6 on 2025-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0020_post_share_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش'),
        ),
    ]
