# Generated by Django 5.2.6 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0021_media_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=600, verbose_name='توضیحات پست'),
        ),
    ]
