# Generated by Django 5.2.6 on 2025-10-04 14:50

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', help_text='78 * 78', keep_meta=True, quality=100, scale=None, size=[78, 78], upload_to='settings/logo/', verbose_name='لوگو')),
                ('open_logo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', help_text='126 * 97', keep_meta=True, quality=100, scale=None, size=[126, 97], upload_to='settings/logo/', verbose_name='لوگو فوتر')),
                ('footer_title1', models.CharField(max_length=20, verbose_name='تیتر')),
                ('footer_text1', models.TextField(max_length=255, verbose_name='محتوا')),
                ('footer_title2', models.CharField(max_length=20, verbose_name='تیتر')),
                ('footer_text2', models.TextField(max_length=100, verbose_name='محتوا')),
                ('footer_img1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='140 * 40', keep_meta=True, null=True, quality=100, scale=None, size=[140, 40], upload_to='settings/section2_images/', verbose_name='عکس اول فوتر')),
                ('footer_img2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='140 * 40', keep_meta=True, null=True, quality=100, scale=None, size=[140, 40], upload_to='settings/section2_images/', verbose_name='عکس دوم فوتر')),
                ('footer_img3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='140 * 40', keep_meta=True, null=True, quality=100, scale=None, size=[140, 40], upload_to='settings/section2_images/', verbose_name='عکس سوم فوتر')),
                ('club_enabled', models.BooleanField(default=True, verbose_name='فعال سازی کلاب')),
                ('club_welcome_email_enabled', models.BooleanField(default=False, verbose_name='ارسال ایمیل خوش آمد')),
                ('club_title', models.CharField(max_length=20, verbose_name='تیتر')),
                ('club_text', models.TextField(max_length=100, verbose_name='محتوا')),
                ('contact_us_title', models.CharField(max_length=20, verbose_name='تیتر')),
                ('contact_us_phone', models.CharField(max_length=25, verbose_name='شماره تلفن')),
                ('contact_us_email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('contact_us_address', models.CharField(max_length=60, verbose_name='آدرس')),
                ('telegram_link', models.CharField(max_length=255, verbose_name='تلگرام')),
                ('whatsapp_link', models.CharField(max_length=255, verbose_name='واتساپ')),
                ('facebook_link', models.CharField(max_length=255, verbose_name='فیسبوک')),
                ('linkedin_link', models.CharField(max_length=255, verbose_name='لینکدین')),
                ('twitter_link', models.CharField(max_length=255, verbose_name='ایکس')),
                ('rights_text', models.TextField(max_length=255, verbose_name='متن حقوق سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
