# Generated by Django 5.2.6 on 2025-10-05 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خبرنامه',
                'verbose_name_plural': 'خبرنامه',
            },
        ),
        migrations.CreateModel(
            name='ClubMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='متن پیام')),
                ('is_ready', models.BooleanField(default=False, verbose_name='آماده ارسال')),
                ('send_to', models.CharField(choices=[('ارسال برای همه', 'ارسال برای همه'), ('ارسال برای کسانی که قبلا این پیام را گرفته اند', 'ارسال برای کسانی که قبلا این پیام را گرفته اند'), ('ارسال برای اعضای جدید', 'ارسال برای اعضای جدید')], max_length=50, verbose_name='ارسال برای')),
                ('sent_to', models.ManyToManyField(related_name='received_messages', to='main.clubmember', verbose_name='ارسال شده برای')),
            ],
            options={
                'verbose_name': 'پیام های خبرنامه',
                'verbose_name_plural': 'پیام های خبرنامه',
            },
        ),
    ]
