# Generated by Django 5.2.6 on 2025-10-05 14:31

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_clubmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='landing_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, help_text='511 * 539', keep_meta=True, quality=100, scale=None, size=[155, 155], upload_to='settings/landing/', verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='landing_subtitle',
            field=models.CharField(default='', help_text='تیتر آبی رنگ', max_length=30, verbose_name='زیرنویس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='landing_text',
            field=models.TextField(default='', max_length=250, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='landing_title',
            field=models.CharField(default='', help_text='تیتر سفید رنگ', max_length=15, verbose_name='تیتر'),
            preserve_default=False,
        ),
    ]
