# Generated by Django 5.2.6 on 2025-10-05 14:34

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_setting_landing_image_setting_landing_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='landing_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', help_text='511 * 539', keep_meta=True, quality=100, scale=None, size=[155, 155], upload_to='settings/landing/', verbose_name='عکس'),
        ),
    ]
