# Generated by Django 5.2.6 on 2025-10-05 16:56

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_setting_landing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='landing_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', help_text='511 * 539', keep_meta=True, quality=100, scale=None, size=[511, 539], upload_to='settings/landing/', verbose_name='عکس'),
        ),
    ]
