# Generated by Django 5.2.6 on 2025-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_setting_landing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section1_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
                ('section2_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section2_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
                ('section3_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section3_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
                ('section4_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section4_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
                ('section5_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section5_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
                ('section6_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section6_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
                ('section7_title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('section7_content', models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
        ),
    ]
