# Generated by Django 5.2.6 on 2025-10-20 20:08

import django_resized.forms
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ad1_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='1', force_format='JPG', help_text='728 * 90', keep_meta=True, quality=100, scale=None, size=[728, 90], upload_to='settings/ads/', verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='ad2_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='1', force_format='JPG', help_text='728 * 90', keep_meta=True, quality=100, scale=None, size=[728, 90], upload_to='settings/ads/', verbose_name='عکس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section5_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_category_sections], verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section6_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_category_sections], verbose_name='محتوا'),
        ),
    ]
