# Generated by Django 5.2.6 on 2025-10-20 20:13

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_setting_ad1_image_setting_ad2_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='ad1_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPG', help_text='728 * 90', keep_meta=True, null=True, quality=100, scale=None, size=[728, 90], upload_to='settings/ads/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ad2_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPG', help_text='728 * 90', keep_meta=True, null=True, quality=100, scale=None, size=[728, 90], upload_to='settings/ads/', verbose_name='عکس'),
        ),
    ]
