# Generated by Django 5.2.6 on 2025-10-20 20:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_setting_ad1_image_alter_setting_ad2_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='ad1_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='728 * 90', keep_meta=True, null=True, quality=100, scale=None, size=[728, 90], upload_to='settings/ads/', verbose_name='تبلیغ اول'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ad2_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='728 * 90', keep_meta=True, null=True, quality=100, scale=None, size=[728, 90], upload_to='settings/ads/', verbose_name='تبلیغ دوم'),
        ),
    ]
