# Generated by Django 5.2.6 on 2025-10-27 20:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_setting_ad1_image_alter_setting_ad2_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='whatsapp_link',
        ),
        migrations.AddField(
            model_name='setting',
            name='aparat_link',
            field=models.CharField(default='aparat.com', max_length=255, verbose_name='آپارات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='eitaa_link',
            field=models.CharField(default='eitaa.com', max_length=255, verbose_name='ایتا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram_link',
            field=models.CharField(default='instagram.com', max_length=255, verbose_name='اینستاگرام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube_link',
            field=models.CharField(default='youtube.com', max_length=255, verbose_name='یوتیوب'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section1_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_artists_section], verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section2_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_artists_section], verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section3_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_section_three], verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section4_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_artists_section], verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='section7_content',
            field=models.CharField(choices=[('recent-posts', 'پست های ترند اخیر'), ('weekly-posts', 'برترین های هفته'), ('new-posts', 'پست های جدید'), ('live-suggestions', 'پیشنهادی های سایت'), ('top-artists', 'هنرمند های برتر'), ('top-album', 'دسته بندی های برتر'), ('top-user-album', 'دسته بندی های پر مخاطب')], max_length=30, validators=[main.models.validate_artists_section], verbose_name='محتوا'),
        ),
    ]
