# Generated by Django 5.2.6 on 2025-10-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_setting_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='footer_text1',
            field=models.TextField(max_length=600, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_text2',
            field=models.TextField(max_length=600, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_title1',
            field=models.CharField(max_length=60, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_title2',
            field=models.CharField(max_length=60, verbose_name='تیتر'),
        ),
    ]
