# Generated by Django 5.2.6 on 2025-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_setting_footer_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmessage',
            name='subject',
            field=models.CharField(default='پیام از ذکرمبین', max_length=120, verbose_name='موضوع'),
        ),
    ]
