# Generated by Django 5.2.6 on 2025-11-02 16:42

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_clubmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='opening_video',
            field=models.FileField(blank=True, null=True, upload_to='MainPage/opening/', validators=[main.models.validate_is_mp4], verbose_name='ویدیو'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='show_opening',
            field=models.BooleanField(default=False, verbose_name='نمایش ویدیو در سایت'),
        ),
    ]
