# Generated by Django 5.2.6 on 2025-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_mainpage_opening_video_mainpage_show_opening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='opening_video',
            new_name='section8_content',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='show_opening',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='section8_show',
            field=models.BooleanField(default=True, verbose_name='نمایش ویدیو صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='section8_title',
            field=models.CharField(default='title', max_length=30, verbose_name='تیتر'),
            preserve_default=False,
        ),
    ]
