# Generated by Django 5.2.6 on 2025-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_opening_video_mainpage_section8_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='section9_show',
            field=models.BooleanField(default=True, verbose_name='نمایش استوری ها'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='section9_title',
            field=models.CharField(default='sec9', max_length=30, verbose_name='تیتر'),
            preserve_default=False,
        ),
    ]
