# Generated by Django 5.2.6 on 2025-11-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_mainpage_section9_show_mainpage_section9_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='section9_show',
        ),
    ]
