# Generated by Django 5.2.6 on 2025-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_mainpage_section9_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer_img1_link',
            field=models.CharField(blank=True, help_text='با https://', max_length=255, verbose_name='لینک عکس اول'),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_img2_link',
            field=models.CharField(blank=True, help_text='با https://', max_length=255, verbose_name='لینک عکس دوم'),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_img3_link',
            field=models.CharField(blank=True, help_text='با https://', max_length=255, verbose_name='لینک عکس سوم'),
        ),
    ]
