# Generated by Django 5.2.6 on 2025-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_setting_footer_img1_link_setting_footer_img2_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='footer_img1_link',
            field=models.CharField(default='https://zekremobin.ir/', help_text='با https://', max_length=255, verbose_name='لینک عکس اول'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_img2_link',
            field=models.CharField(default='https://zekremobin.ir/', help_text='با https://', max_length=2, verbose_name='لینک عکس دوم'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='footer_img3_link',
            field=models.CharField(default='https://zekremobin.ir/', help_text='با https://', max_length=255, verbose_name='لینک عکس سوم'),
        ),
    ]
