# Generated by Django 5.2.6 on 2025-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_setting_footer_img1_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='footer_img2_link',
            field=models.CharField(default='https://zekremobin.ir/', help_text='با https://', max_length=255, verbose_name='لینک عکس دوم'),
        ),
    ]
