# Generated by Django 5.2.6 on 2025-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_setting_footer_img2_link'),
        ('media_center', '0020_post_share_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='section10_content',
            field=models.ManyToManyField(to='media_center.post', verbose_name='پست ها'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='section10_title',
            field=models.CharField(default='Manual Posts', max_length=30, verbose_name='تیتر'),
            preserve_default=False,
        ),
    ]
