# Generated by Django 5.2.6 on 2025-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_mainpage_section10_content_mainpage_section10_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ad1_link',
            field=models.CharField(default='https://zekremobin.ir/', help_text='با https://', max_length=255, verbose_name='لینک تبلیغ اول'),
        ),
        migrations.AddField(
            model_name='setting',
            name='ad2_link',
            field=models.CharField(default='https://zekremobin.ir/', help_text='با https://', max_length=255, verbose_name='لینک تبلیغ دوم'),
        ),
    ]
