# Generated by Django 5.2.6 on 2025-11-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_setting_ad1_link_setting_ad2_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='ad1_link',
            field=models.CharField(blank=True, default='https://zekremobin.ir/', help_text='با https://', max_length=255, null=True, verbose_name='لینک تبلیغ اول'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='ad2_link',
            field=models.CharField(blank=True, default='https://zekremobin.ir/', help_text='با https://', max_length=255, null=True, verbose_name='لینک تبلیغ دوم'),
        ),
    ]
