# Generated by Django 5.2.6 on 2025-10-30 14:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='conclusion',
            field=tinymce.models.HTMLField(blank=True, help_text='متن بعد از نظر نویسنده', verbose_name='نتیجه گیری'),
        ),
    ]
