# Generated by Django 5.2.6 on 2025-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
    ]
